# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b31abd5066a944ecf56b4a1ef69b2704ea02bbb553a4eac7bc8f38dd25050379441f28b0639abe48bc68b8bbd8bb8d8528185b5ef70c44a662787ea44ae300

test:
  secret_key_base: e8cb25fcef976375dd1b26eec241a7084be2f217c416c6e79d83cc2566199329ff86783176891e421c4698129b347a1665b9c02dc38859dc0953159abcbca5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
